python3: can't open file '/data/data/com.termux/files/home/godai-genesis/bots/autoblogger.py': [Errno 2] No such file or directory
